version: '3.5'

services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      PGDATA: /data/postgres
    volumes:
      - ./backend/database:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_PASS}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./backend/pgadmin:/var/lib/pgadmin
    ports:
      - "3001:80"
    restart: unless-stopped

  backend:
    image: node
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - database
    command: npm run dev
    env_file:
      - ./.env
    environment:
      - DB_HOST=database
    restart: unless-stopped
    expose:
      - "3000"
  
  frontend:
    image: nginx
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "8080:80"
    restart: unless-stopped
